-- 193 — ProducerHome: platform-wide "what's new" feed + per-workspace weekly
-- coaching note.
--
-- Context: .claude/decisions.md 2026-07-29 ("ProducerHome"). Bernard ships
-- multiple PRs a day; the only prior "what's new" channel was a hand-maintained
-- release-notes.json that had been stale since 2026-06-01. This replaces it for
-- role-targeted announcements (the deploy-reload modal mechanism, useVersionCheck
-- + UpdateAvailableModal, is unrelated and stays as-is).
--
-- product_updates is GLOBAL, not per-workspace — Bernard is one deployment
-- serving every tenant, so a shipped feature is the same news for all of them.
-- `roles` is a text[] of audience tags ('producer','clinician','owner'); an
-- empty array means "everyone". Generated by scripts/generate-product-updates.mjs
-- (nightly, reads merged PRs, writes plain-language entries) — see that script's
-- header for how it's scheduled.
CREATE TABLE IF NOT EXISTS public.product_updates (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz NOT NULL DEFAULT now(),
  summary     text NOT NULL,
  roles       text[] NOT NULL DEFAULT '{}',
  page_hint   text,
  source_pr   integer,
  source_sha  text
);

CREATE INDEX IF NOT EXISTS product_updates_created_at_idx ON public.product_updates (created_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_updates TO service_role;

-- workspace_coaching_notes — one cached weekly note per workspace (P4). A
-- separate table rather than a workspaces JSONB column so history is kept
-- (useful for the 2026-09-15 kill-criterion check: did the queue + note
-- actually get read weekly).
CREATE TABLE IF NOT EXISTS public.workspace_coaching_notes (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id  uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  week_monday   date NOT NULL,
  note          text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, week_monday)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.workspace_coaching_notes TO service_role;
